### ISSUE TITLE
400 bad request console error

### ISSUE THREAD

**Issue by eliazzo** [enBloc-org/kindly#168] opened 2024-04-12 09:26 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
<hr>

# Expected Behaviour

While the page is behaving as desired, ideally we want to remove the errors from the console.

# Current Behaviour

The request succeeds but only after an initial fail.
🪲
<img width="770" alt="Screenshot 2024-04-12 at 10 23 20" src="https://github.com/enBloc-org/kindly/assets/114364165/bcd7ca92-9528-40af-9ee6-2766c7482235">

<img width="437" alt="Screenshot 2024-04-12 at 10 24 35" src="https://github.com/enBloc-org/kindly/assets/114364165/eace05ad-d8dc-4273-b6ad-d57c2c34ec5c">

**Comment by nichgalzin** [comment] 2024-05-17 10:17
We think the issue may be cause be the database call is happening. Some possible solutions could entail: 
- Moving where the call happens (The context provider?)
- Add a boundary/loading state to handle the database call before trying to render the component.

**Comment by AnyaVeselova** [comment] 2024-09-19 17:13
!request

**Comment by AnyaVeselova** [comment] 2024-09-20 03:31
Hi guys! I took on the issue but I haven't found the error. As this API doesn't exist anymore, would I be right in assuming that db was changed and the problem isn't relevant? It inspired me to fix a similar bug :) Thank you!

**Comment by camelPhonso** [comment] 2024-09-20 06:36
> Hi guys! I took on the issue but I haven't found the error. As this API doesn't exist anymore, would I be right in assuming that db was changed and the problem isn't relevant? It inspired me to fix a similar bug though:) Thank you!

Hi @AnyaVeselova - the database is implementing the same service but we have updated the dev environment with different seed data and moved the client service to a singleton pattern which might have avoided this.

@nichgalzin could you have a look to confirm that the original error is gone? If Anya doesn't find it this could either be solved or be a question of individual set up leading to it. Let's try to confirm which one and close this ticket if it's not relevant anymore

**Comment by camelPhonso** [comment] 2024-09-20 09:48
verified this is resolved

**Closed by camelPhonso** 2024-09-20 09:48 UTC
Labels: 🪲 bug, 😱 help wanted, 🧑‍💻 assigned
