### ISSUE TITLE
Preserve formatting in new messages

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#154] opened 2024-04-05 11:19 UTC
# Expected Behaviour

If a user uses the `MessageForm.tsx` component to create a new message it should be displayed in `CurrentConversation.tsx` with the same formatting as it was submitted. For example, a user should be able to submit a text with the following format:

>Hey,
> 
>How've you been?
>
> Dad.

# Current Behaviour
When a user submits a new message through the `MessageForm.tsx` component it gets formatted into a single line of text.

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Navigate to your conversations
2. Open any conversation
3. Type a message that includes an empty line or indentations
4. Once sent, the message will show as a single line of text

**Comment by JasonWarrenUK** [comment] 2024-04-09 10:32
@camelPhonso Can you assign this issue to me?

**Comment by JasonWarrenUK** [comment] 2024-04-09 13:49
Okay so at this point the message is definitely being correctly transmitted right up to CurrentConversation.tsx and I'm now pretty sure the problem is within the MessageCard bits.

**Closed** 2024-04-09 16:50 UTC
Labels: good first issue
